# Generated by Django 5.0.4 on 2024-05-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ResourceManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutasDeEntrega',
            fields=[
                ('ruta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('distancia_total_recorrida', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleRutaDeEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden_de_entrega', models.IntegerField()),
                ('distancia_recorrida_al_punto', models.DecimalField(decimal_places=3, max_digits=9)),
                ('demanda_a_entregar', models.DecimalField(decimal_places=3, max_digits=9)),
                ('punto_de_entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceManagement.puntodeentrega')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Optimizer.rutasdeentrega')),
            ],
        ),
    ]
