# Generated by Django 5.0.4 on 2024-05-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Optimizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallerutadeentrega',
            name='estado',
            field=models.CharField(choices=[('procesada', 'Procesada'), ('finalizada', 'Finalizada')], default='procesada', max_length=255),
        ),
    ]
