# Generated by Django 5.0.4 on 2024-05-08 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('numero_de_telefono', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Demanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso_kg', models.DecimalField(decimal_places=3, max_digits=9)),
                ('fecha_creada', models.DateTimeField(auto_now_add=True)),
                ('descripción', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('asignada', 'Asignada'), ('entregada', 'Entregada')], default='pendiente', max_length=255)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceManagement.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='PuntoDeEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=255)),
                ('latitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud', models.DecimalField(decimal_places=6, max_digits=9)),
                ('numero_de_telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesar', 'Procesar'), ('optimizado', 'Optimizado')], default='procesar', max_length=255)),
                ('demanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceManagement.demanda')),
            ],
            options={
                'verbose_name': 'Punto de Entrega',
                'verbose_name_plural': 'Puntos de Entregas',
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('matricula', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('capacidad_de_carga', models.IntegerField()),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('no_disponible', 'No disponible')], default='disponible', max_length=255)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ResourceManagement.deposito')),
            ],
        ),
    ]
